### ISSUE TITLE
Fix regex -- currently too restrictive

### ISSUE THREAD

**Issue by jay-tyler** [jay-tyler/data-petting-zoo#50]
Our regex is flawed because I screwed up. We should add the ability to match any number of characters to the end and beginning of each regex.

`"acPaccPockS": ("(Ac)", "(Acc)", "(ock$)")` should become
`"acPaccPockS": ("(.*\s*Ac.*)", "(.*\s*Acc.*)", "(.*\w+ock($|[\s+.*]))")`

Formula for inside capture group (for these, 'namefrag' is the fragment being matched):
- prefix:    `.*\s*Namefrag.*`
- suffix:   `.*\w+namefrag($|[\s+.*])`
- infix:     `.+namefrag.+`
- 'all'-fix:    `.*Namefrag.*`
- 'unknown'-fix:   `.*[Nn]amefrag.*`

**Comment by jay-tyler** [comment]
Also, let's do this in the rules.py file this time, not the google doc.

**Comment by jay-tyler** [comment]
Finished for A words.

**Comment by SakiFu** [comment]
Done fixing and pushed to my branch.
